version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379     