version: '3.8'

services:

  db:
    image: mongo
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  
  test-db:
    image: mongo
    container_name: test-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379     